config/routes.rb
Cantyshanty::Application.routes.draw do

  # tags
  match 'tags/:slug' => 'tags#show', :as => :tag
  match 'tags' => 'tags#index', :as => :tag_cloud

  # entries
  match '_*slug/beacon' => 'home#beacon', :format => :gif, :as => :beacon
  match '_*slug' => 'home#image', :as => :short

  # search
  match 'search' => 'search#index', :as => :search

  # legacy views
  match 'tc/:slug' => 'legacy#image'
  match 'page:page_num' => 'legacy#page'
  match 'tag/:slug' => 'legacy#tag'
  match 'tag' => 'legacy#tag_cloud'

  # posts admin
  resources :posts do
    put 'publish', :on => :member
    get 'attributed', :on => :collection
    get 'drafts', :on => :collection
    get 'published', :on => :collection
    get 'search', :on => :collection
    get 'unattributed', :on => :collection
    get 'unpublished', :on => :collection
  end

  # home
  match 'about' => 'home#about', :as => :about
  match 'rss' => 'home#rss', :format => :xml, :as => :rss
  root :to => "home#index"

  # errors
  match "/404", :to => "errors#not_found"
  match "/422", :to => "errors#rejected"
  match "/500", :to => "errors#internal_server"

end

app/views/layouts/_post.html.erb
<article class="<%= format %> <%= links %>" style="width: <% if post.image.width(format) %><%= post.image.width(format) - 80 %>px;<% else %>80%<% end %>">
	<% if post.title %>
		<% if links == 'public' and post.slug %>
			<h2><a href="<%= short_url(:slug => post.slug) %>"><%= post.title %></a></h2>
		<% elsif links == 'admin' %>
			<h2><a href="<%= post_url(post) %>"><%= post.title %></a></h2>
	    <% else %>
			<h2><%= post.title %></h2>
		<% end %>
	<% end %>

	<div class="image">
		<% if links == 'public' and post.slug %>
			<a href="<%= short_url(:slug => post.slug) %>" title="<%= post.title %>"><%= image_tag post.image.url(format), :alt => post.title, :size => post.image.image_size(format) %></a>
		<% elsif links == 'admin' %>
			<a href="<%= post_url(post) %>" title="<%= post.title %>"><%= image_tag post.image.url(format), :alt => post.title, :size => post.image.image_size(format) %></a>
		<% else %>
			<%= image_tag post.image.url(format), :alt => post.title, :size => post.image.image_size(format) %>
		<% end %>
	</div>

	<% if post.tags.size > 0 %>
		<ul class="tags">
			<% post.tags.each do |tag| %><li><a href="<%= tag_url(:slug => tag.name) %>"><%= tag %></a></li> <% end %>
		</ul>
	<% end %>

	<% if post.sourced %><p class="source"><em>source:</em> <%= link_to post.source_title, post.source_url %></p><% end %>
	
	<% if post.slug %><p class="permanent"><a href="<%= short_url(:slug => post.slug) %>">Permalink</a></p><% end %>
</article>

app/views/layouts/admin.html.erb
<% content_for :scripts do %>
    <%= javascript_include_tag "application" %>
<% end %>

<% content_for :body_class do %>admin<% end %>

<% content_for :navigation do %>
	<ul>
	    <li class="<% if @status == 'backlog' %>active<% end %>"><a href="<%= posts_path %>"><span>Backlog</span> <em>(<%= @backlog_count %>)</em></a></li>
		<li class="<% if @status == 'drafts' %>active<% end %>"><a href="<%= drafts_posts_path %>"><span>Drafts</span> <em>(<%= @draft_count %>)</em></a></li>
		<li class="<% if @status == 'published' %>active<% end %> not-mobile"><a href="<%= published_posts_path %>"><span>Published</span> <em>(<%= @published_count %>)</em></a></li>
		<li class="<% if @status == 'unattributed' %>active<% end %> not-mobile"><a href="<%= unattributed_posts_path %>"><span>Unattributed</span> <em>(<%= @unattributed_count %>)</em></a></li>
		<li class="<% if @status == 'attributed' %>active<% end %> not-mobile"><a href="<%= attributed_posts_path %>"><span>Attributed</span> <em>(<%= @attributed_count %>)</em></a></li>
		<li class="<% if @status == 'unpublished' %>active<% end %> not-mobile"><a href="<%= unpublished_posts_path %>"><span>Unpublished</span> <em>(<%= @unpublished_count %>)</em></a></li>
		<li class="<% if @status == 'upload' %>active<% end %>"><a href="<%= new_post_path %>">Upload</a></li>
	</ul>

	<form action="<%= search_posts_path %>" method="GET" class="search">
		<input type="text" placeholder="Search" name="q" value="<%= params[:q] %>" />
	</form>
<% end %>

<% content_for :footer do %>
	<% if @status == 'backlog' %>
		<div class="pagination"><a class="backlog" href="<%= posts_url %>">Load new backlog images</a></div>
	<% else %>
		<% if @posts %>
			<%= will_paginate @posts %>
		<% end %>
	<% end %>
<% end %>

<%= render :template => 'layouts/application' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><% if content_for?(:title) %><%= yield(:title) %> | <% end %>Canty Shanty</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="author" content="Home Improvement Troll" />
		<meta name="description" content="This could be my house" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
		<meta name="apple-mobile-web-app-capable" content="yes" />

		<%= stylesheet_link_tag("application") %>
		<%= content_for?(:styles) ? yield(:styles) : '' %>
		<%= content_for?(:scripts) ? yield(:scripts) : '' %>

		<link rel="shortcut icon" href="<%= image_path 'favicon.ico' %>" />
		<link rel="apple-touch-icon" href="<%= image_path 'apple-touch-icon.png' %>" />
		<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'apple-touch-icon-57x57.png' %>" />
		<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'apple-touch-icon-72x72.png' %>" />
		<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'apple-touch-icon-114x114.png' %>" />
        <!-- <link rel="apple-touch-startup-image" href="/startup.png"> -->

		<link rel="alternate" type="application/rss+xml" title="RSS" href="<%= rss_url %>">

    <%= content_for?(:meta) ? yield(:meta) : '' %>

		<% if content_for?(:canonical) %><link rel="canonical" href="<%= yield(:canonical) %>" /><% end %>

		<%= csrf_meta_tags %>

		<% if content_for?(:analytics) %><%= yield(:analytics) %><% end %>
	</head>
	<body<% if content_for?(:body_class) %> class="<%= yield(:body_class) %>"<% end %>>
		<header>
			<h1><a href="<%= root_url %>">Canty Shanty</a></h1>
			<nav class="primary">
				<ul>
					<li class="home"><a href="<%= root_url %>">Canty Shanty</a></li>
					<li class="about"><a href="<%= about_url %>">About</a></li>
					<li class="tags"><a href="<%= tag_cloud_url %>">Tags</a></li>
					<li class="twitter"><a href="http://twitter.com/cantyshanty">Twitter</a></li>
				</ul>
			</nav>
		</header>

		<div class="content">

			<% if content_for?(:navigation) %>
			<nav class="secondary">
				<%= yield(:navigation) %>
			</nav>
			<% end %>

			<% if content_for?(:content) %>
			<section>
				<%= yield(:content) %>
			</section>
			<% end %>
		</div>

		<footer>
			<% if content_for?(:footer) %><%= yield(:footer) %><% end %>

			<p class="copyright">&copy; Images are copyright of their respective owners. I just don't know who they are.</p>
		</footer>
	</body>
</html>

app/views/layouts/public.html.erb
<% if content_for?(:analytics) %><%= yield(:analytics) %><% end %>

<% content_for :body_class do %>public<% end %>

<% content_for :analytics do %>
	<script type="text/javascript">
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', '<%= GoogleAnalytics::ACCOUNT %>']);
		_gaq.push(['_trackPageview']);

		(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();
	</script>	
<% end %>

<% content_for :navigation do %>
	<form action="<%= search_url %>" method="GET" class="search">
		<input type="text" placeholder="Search" name="q" value="<%= params[:q] %>" />
	</form>
<% end %>

<% content_for :content do %>
	<%= yield %>
<% end %>

<% content_for :footer do %>
	<% if @posts %>
		<%= will_paginate @posts,
			:previous_label => '&larr;<span> Previous</span>',
			:next_label => '<span>Next </span>&rarr;' %>
	<% end %>

	<% if @post %>
		<div class="pagination">
			<% if @post.previous %><a class="previous_page" href="<%= short_url(:slug => @post.previous.slug) %>">&larr;<span> <%= @post.previous.title %></span></a><% end %>
			<% if @post.next %><a class="next_page" href="<%= short_url(:slug => @post.next.slug) %>"><span><%= @post.next.title %> </span>&rarr;</a><% end %>
		</div>
	<% end %>
<% end %>

<%= render :template => 'layouts/application' %>